# GKE returns Major:"1", Minor:"10+"
{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.mysql.service.diamond.sensetime.com
  labels:
    {{- include "kubedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: mysql.validators.mysql.service.diamond.sensetime.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.mysql.service.diamond.sensetime.com/v1alpha1/mysqlvalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - apiGroups: ["mysql.service.diamond.sensetime.com"]
    apiVersions: ["*"]
    resources: ["mysqls"]
    operations: ["CREATE", "UPDATE", "DELETE"]
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
- name: snapshot.validators.mysql.service.diamond.sensetime.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.mysql.service.diamond.sensetime.com/v1alpha1/snapshotvalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - apiGroups: ["mysql.service.diamond.sensetime.com"]
    apiVersions: ["*"]
    resources: ["snapshots"]
    operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
- name: dormantdatabase.validators.mysql.service.diamond.sensetime.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.mysql.service.diamond.sensetime.com/v1alpha1/dormantdatabasevalidators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - apiGroups: ["mysql.service.diamond.sensetime.com"]
    apiVersions: ["*"]
    resources: ["dormantdatabases"]
    operations: ["CREATE", "UPDATE", "DELETE"]
  failurePolicy: Fail
{{- if and (ge $major 1) (ge $minor 12) }}
  sideEffects: None
{{- end }}
{{ end }}
