# GKE returns Major:"1", Minor:"10+"
{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- if .Values.apiserver.enableMutatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutators.mysql.service.diamond.sensetime.com
  labels:
    {{- include "kubedb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
webhooks:
- name: mysql.mutators.mysql.service.diamond.sensetime.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/mutators.mysql.service.diamond.sensetime.com/v1alpha1/mysqlmutators
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - apiGroups: ["mysql.service.diamond.sensetime.com"]
    apiVersions: ["*"]
    resources: ["mysqls"]
    operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
{{ end }}
