{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb:core:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - mysql.service.diamond.sensetime.com
  - catalog.mysql.service.diamond.sensetime.com
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedb:core:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - mysql.service.diamond.sensetime.com
  resources:
  - mysqls
  - snapshots
  verbs: ["*"]
- apiGroups:
  - mysql.service.diamond.sensetime.com
  resources:
  - dormantdatabases
  verbs: ["get", "list", "watch"]
- apiGroups:
  - catalog.mysql.service.diamond.sensetime.com
  resources:
  - mysqlversions
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubedb:core:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - mysql.service.diamond.sensetime.com
  resources:
  - mysqls
  - snapshots
  verbs: ["get", "list", "watch"]
- apiGroups:
  - catalog.mysql.service.diamond.sensetime.com
  resources:
  - mysqlversions
  verbs: ["get", "list", "watch"]
{{ end }}
