apiVersion: v1
data:
  mysql-binding.yaml: |
    apiVersion: servicecatalog.k8s.io/v1beta1
    kind: ServiceBinding
    metadata:
      name: {{ .Values.servicebinding.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app: mysql-service-broker
    spec:
      instanceRef:
        name: {{ .Values.serviceinstance.name }}
      secretName: {{ .Values.secretName }}
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-binding-configmap
  namespace: {{ .Release.Namespace }}