apiVersion: v1
data:
  mysql-instance.yaml: |
    apiVersion: servicecatalog.k8s.io/v1beta1
    kind: ServiceInstance
    metadata:
      name: {{ .Values.serviceinstance.name }}
      namespace: {{ .Release.Namespace }}
      labels:
        app: mysql-service-broker
    spec:
      clusterServiceClassExternalName: {{ .Values.serviceclass }}
      clusterServicePlanExternalName: {{ .Values.serviceplan }}
      parameters:
        metadata:
          labels:
            app: my-mysql
        spec:
          version: {{ .Values.mysqlversion }}
          storageType: {{ .Values.storageType }}
          storage:
            accessModes:
              - {{ .Values.storage.accessModes }}
            resources:
              requests:
                storage: {{ .Values.storage.resources.requests.storage }}
          terminationPolicy: {{ .Values.terminationPolicy }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-instance-configmap
  namespace: {{ .Release.Namespace }}
  