apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Values.job.serviceAccountName }}
      containers:
      - name: pro-bind-job
        image: appscode/kubectl:v1.12
        command: ["sh", "-c", "kubectl create -f /etc/config1/mysql-instance.yaml;i=0;while [ $i -le 60 ];do kubectl get pod {{ .Values.serviceinstance.name }}-0 -n {{ .Release.Namespace }} | grep -q Running;if [ $? = 0 ];then  break;fi;sleep 5;i=$((i+1));done;kubectl create -f /etc/config2/mysql-binding.yaml;"]
        volumeMounts:
          - name: instance-config
            mountPath: /etc/config1
          - name: binding-config
            mountPath: /etc/config2
      volumes:
        - name: instance-config
          configMap:
            name: {{.Release.Name}}-instance-configmap
        - name: binding-config
          configMap:
            name: {{.Release.Name}}-binding-configmap
          
      
