{{ if .Values.catalog.mysql }}
apiVersion: catalog.mysql.service.diamond.sensetime.com/v1alpha1
kind: MySQLVersion
metadata:
  name: "8.0.14-aarch64"
  labels:
    {{- include "kubedb-catalog.labels" . | nindent 4 }}
spec:
  version: "8.0.14"
  db:
    image: "{{ .Values.dockerRegistry }}/mysql-server:8.0.14-aarch64-root"
  exporter:
    image: "{{ .Values.dockerRegistry }}/mysqld-exporter:v0.11.0-aarch64-root"
  tools:
    image: "{{ .Values.dockerRegistry }}/mysql-tools:8.0.14-aarch64-root"
  initContainer:
    image: "{{ .Values.dockerRegistry }}/busybox:aarch64-root"
  podSecurityPolicies:
    databasePolicyName: mysql-db
    snapshotterPolicyName: mysql-snapshot

{{ end }}
