apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-service-account-binding
  labels:
    app: {{ .Values.sp_name }}-service-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mysql-service-account
    namespace: {{ .Values.namespace }}
