apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: {{ .Values.sp_name }}-service-exporter
    prometheus: prometheus
  name: {{ .Values.sp_name }}-service-exporter
  namespace: {{ .Values.namespace }}
spec:
  endpoints:
  - interval: 30s
    port: server
  selector:
    matchLabels:
      app: {{ .Values.sp_name }}-service-exporter
