name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Hello world action step
      uses: xuhaowang/githubActionJS@master
      id: hello
      with:
        who-to-greet: 'World blabla'
      
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    # - uses: engineerd/setup-kind@v0.1.0
    # - name: Testing
    #   run: |
    #     export KUBECONFIG="$(kind get kubeconfig-path)"
    #     echo $KUBECONFIG
    #     kubectl cluster-info
    #     kubectl get pods -n kube-system
    
    # - name: Run ansible-playbook
    #   run: |
    #     export KUBECONFIG="$(kind get kubeconfig-path)"
    #     echo $KUBECONFIG
    #     cd $GITHUB_WORKSPACE
    #     ansible-playbook -v test.yml
    
